# Generated by Django 5.0.6 on 2024-06-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Nombres')),
                ('lastname', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('dui', models.CharField(default='', max_length=50, unique=True, verbose_name='Dui')),
                ('wallet', models.CharField(max_length=500, verbose_name='Wallet')),
                ('private_key', models.CharField(max_length=500, verbose_name='Private key')),
                ('password', models.CharField(max_length=20, verbose_name='Contraseña')),
            ],
        ),
    ]
