# Generated by Django 5.0.6 on 2024-06-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prescrypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dui',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='DUI'),
        ),
        migrations.AlterField(
            model_name='users',
            name='private_key',
            field=models.CharField(max_length=500, unique=True, verbose_name='Private key'),
        ),
        migrations.AlterField(
            model_name='users',
            name='wallet',
            field=models.CharField(max_length=500, unique=True, verbose_name='Wallet'),
        ),
    ]
